/*
 * @author U079754 A. Emre Zorlu
 * @date May 27, 2016
 */
package com.sgo.depanalyze.hibernate.datamodel;

// Generated Oct 23, 2013 10:18:39 AM by Hibernate Tools 3.4.0.CR1
/**
 * DepHmnServices generated by hbm2java.
 * 
 * @author U065352-Selçuk Giray ÖZDAMAR
 * @since Nov 11, 2013 10:14:07 AM
 */
public class HmnDepServiceInterface extends HmnDepDatamodel implements java.io.Serializable {
    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = -254999111802042445L;
    /** The execution id. */
    private Long executionId;
    /** The service class name. */
    private String className;
    /** The service interface name. */
    private String interfaceName;
    /** The artifact id. */
    private Long artifactId;

    /**
     * Instantiates a new hmn dep service interface.
     * 
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public HmnDepServiceInterface() {
        super();
    }

    /**
     * Instantiates a new hmn dep service interface.
     * 
     * @param id
     *            the id
     * @param className
     *            the class name
     * @param interfaceName
     *            the interface name
     * @param executionId
     *            the execution id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public HmnDepServiceInterface(Long id, String className, String interfaceName, Long executionId, Long artifactId) {
        super(id);
        this.executionId = executionId;
        this.className = className;
        this.interfaceName = interfaceName;
        this.artifactId = artifactId;
    }

    /**
     * Gets the class name.
     * <p>
     * </p>
     * 
     * @return the class name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 12:50:13 PM
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the class name.
     * <p>
     * </p>
     * 
     * @param className
     *            the new class name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 12:50:13 PM
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * Gets the interface name.
     * <p>
     * </p>
     * 
     * @return the interface name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 12:50:13 PM
     */
    public String getInterfaceName() {
        return interfaceName;
    }

    /**
     * Sets the interface name.
     * <p>
     * </p>
     * 
     * @param interfaceName
     *            the new interface name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 12:50:13 PM
     */
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName;
    }

    /**
     * Sets the execution id.
     * <p>
     * </p>
     * 
     * @param executionId
     *            the new execution id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 19, 2013 4:39:42 PM
     */
    public void setExecutionId(Long executionId) {
        this.executionId = executionId;
    }

    /**
     * Gets the execution id.
     * <p>
     * </p>
     * 
     * @return the execution id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 19, 2013 4:39:42 PM
     */
    public Long getExecutionId() {
        return executionId;
    }

    /**
     * @author U079754 A. Emre Zorlu
     * @since May 27, 2016
     * @param artifactId
     *            the artifactId to set
     */
    public void setArtifactId(Long artifactId) {
        this.artifactId = artifactId;
    }

    /**
     * @author U079754 A. Emre Zorlu
     * @since May 27, 2016
     * @return the artifactId
     */
    public Long getArtifactId() {
        return artifactId;
    }
}
