package com.sgo.depanalyze.hibernate.datamodel;

// Generated Oct 24, 2013 2:53:28 PM by Hibernate Tools 3.4.0.CR1
/**
 * DepHmnServiceClasses generated by hbm2java.
 * 
 * @author U065352-Selçuk Giray ÖZDAMAR
 * @since Nov 11, 2013 10:14:06 AM
 */
public class HmnDepServiceClass extends HmnDepDatamodel implements java.io.Serializable {
    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 9162481926120772626L;
    /** The class name. */
    private String className;
    /** The artifact id. */
    private Long artifactId;
    /** The execution id. */
    private Long executionId;

    /**
     * Instantiates a new hmn dep service class.
     * 
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:06 AM
     */
    public HmnDepServiceClass() {
        super();
    }

    /**
     * Instantiates a new hmn dep service class.
     * 
     * @param id
     *            the id
     * @param className
     *            the class name
     * @param artifactId
     *            the artifact id
     * @param executionId
     *            the execution id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:06 AM
     */
    public HmnDepServiceClass(Long id, String className, Long artifactId, Long executionId) {
        super(id);
        this.executionId = executionId;
        this.className = className;
        this.artifactId = artifactId;
    }

    /**
     * Gets the class name.
     * <p>
     * </p>
     * 
     * @return the class name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public String getClassName() {
        return this.className;
    }

    /**
     * Sets the class name.
     * <p>
     * </p>
     * 
     * @param className
     *            the new class name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * Gets the artifact id.
     * <p>
     * </p>
     * 
     * @return the artifact id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public Long getArtifactId() {
        return this.artifactId;
    }

    /**
     * Sets the artifact id.
     * <p>
     * </p>
     * 
     * @param artifactId
     *            the new artifact id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setArtifactId(Long artifactId) {
        this.artifactId = artifactId;
    }

    /**
     * Sets the execution id.
     * <p>
     * </p>
     * 
     * @param executionId
     *            the new execution id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 19, 2013 4:39:27 PM
     */
    public void setExecutionId(Long executionId) {
        this.executionId = executionId;
    }

    /**
     * Gets the execution id.
     * <p>
     * </p>
     * 
     * @return the execution id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 19, 2013 4:39:27 PM
     */
    public Long getExecutionId() {
        return executionId;
    }
}
