/*
 * @author U079754 A. Emre Zorlu
 * @date Jun 7, 2016
 */
package com.sgo.depanalyze.hibernate.datamodel;

// Generated Oct 31, 2013 3:14:10 PM by Hibernate Tools 3.4.0.CR1
/**
 * DepHmnPlsqlDepend generated by hbm2java.
 * 
 * @author U065352-Selçuk Giray ÖZDAMAR
 * @since Nov 11, 2013 10:14:07 AM
 */
public class HmnDepPlsqlDependency extends HmnDepDatamodel implements java.io.Serializable {
    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 8468877072227635380L;
    /** The service class. */
    private String serviceClass;
    /** The service method. */
    private String serviceMethod;
    /** The package name. */
    private String packageName;
    /** The proc name. */
    private String procName;
    /** The dependency level. */
    private Integer dependencyLevel;
    /** The dependency path. */
    private String dependencyPath;
    /** The execution id. */
    private Long executionId;
    /** The artifact id. */
    private Long artifactId;

    /**
     * Instantiates a new hmn dep plsql dependency.
     * 
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public HmnDepPlsqlDependency() {
        super();
    }

    /**
     * Instantiates a new hmn dep plsql dependency.
     * 
     * @param id
     *            the id
     * @param serviceClass
     *            the service class
     * @param serviceMethod
     *            the service method
     * @param packageName
     *            the package name
     * @param procName
     *            the proc name
     * @param depLevel
     *            the dep level
     * @param depPath
     *            the dep path
     * @param executionId
     *            the execution id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public HmnDepPlsqlDependency(Long id, String serviceClass, String serviceMethod, String packageName, String procName, Integer depLevel, String depPath, Long executionId, Long artifactId) {
        super(id);
        this.executionId = executionId;
        this.serviceClass = serviceClass;
        this.serviceMethod = serviceMethod;
        this.packageName = packageName;
        this.procName = procName;
        this.dependencyLevel = depLevel;
        this.dependencyPath = depPath;
        this.artifactId = artifactId;
    }

    /**
     * Gets the service class.
     * <p>
     * </p>
     * 
     * @return the service class
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public String getServiceClass() {
        return this.serviceClass;
    }

    /**
     * Sets the service class.
     * <p>
     * </p>
     * 
     * @param serviceClass
     *            the new service class
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setServiceClass(String serviceClass) {
        this.serviceClass = serviceClass;
    }

    /**
     * Gets the service method.
     * <p>
     * </p>
     * 
     * @return the service method
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public String getServiceMethod() {
        return this.serviceMethod;
    }

    /**
     * Sets the service method.
     * <p>
     * </p>
     * 
     * @param serviceMethod
     *            the new service method
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setServiceMethod(String serviceMethod) {
        this.serviceMethod = serviceMethod;
    }

    /**
     * Gets the package name.
     * <p>
     * </p>
     * 
     * @return the package name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public String getPackageName() {
        return this.packageName;
    }

    /**
     * Sets the package name.
     * <p>
     * </p>
     * 
     * @param packageName
     *            the new package name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    /**
     * Gets the proc name.
     * <p>
     * </p>
     * 
     * @return the proc name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public String getProcName() {
        return this.procName;
    }

    /**
     * Sets the proc name.
     * <p>
     * </p>
     * 
     * @param procName
     *            the new proc name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setProcName(String procName) {
        this.procName = procName;
    }

    /**
     * Gets the dependency path.
     * <p>
     * </p>
     * 
     * @return the dependency path
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public String getDependencyPath() {
        return this.dependencyPath;
    }

    /**
     * Sets the dependency path.
     * <p>
     * </p>
     * 
     * @param dependencyPath
     *            the new dependency path
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setDependencyPath(String dependencyPath) {
        this.dependencyPath = dependencyPath;
    }

    /**
     * Sets the dependency level.
     * <p>
     * </p>
     * 
     * @param dependencyLevel
     *            the new dependency level
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setDependencyLevel(Integer dependencyLevel) {
        this.dependencyLevel = dependencyLevel;
    }

    /**
     * Gets the dependency level.
     * <p>
     * </p>
     * 
     * @return the dependency level
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public Integer getDependencyLevel() {
        return dependencyLevel;
    }

    /**
     * Sets the execution id.
     * <p>
     * </p>
     * 
     * @param executionId
     *            the new execution id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 19, 2013 4:39:08 PM
     */
    public void setExecutionId(Long executionId) {
        this.executionId = executionId;
    }

    /**
     * Gets the execution id.
     * <p>
     * </p>
     * 
     * @return the execution id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 19, 2013 4:39:08 PM
     */
    public Long getExecutionId() {
        return executionId;
    }

    /**
     * @author U079754 A. Emre Zorlu
     * @since Jun 7, 2016
     * @param artifactId
     *            the artifactId to set
     */
    public void setArtifactId(Long artifactId) {
        this.artifactId = artifactId;
    }

    /**
     * @author U079754 A. Emre Zorlu
     * @since Jun 7, 2016
     * @return the artifactId
     */
    public Long getArtifactId() {
        return artifactId;
    }
}
