/*
 * @author U079754 A. Emre Zorlu
 * @date Jun 7, 2016
 */
package com.sgo.depanalyze.hibernate.datamodel;

// Generated Oct 23, 2013 10:18:39 AM by Hibernate Tools 3.4.0.CR1
/**
 * DepHmnServices generated by hbm2java.
 * 
 * @author U065352-Selçuk Giray ÖZDAMAR
 * @since Nov 11, 2013 10:14:07 AM
 */
public class HmnDepServiceSuperClass extends HmnDepDatamodel implements java.io.Serializable {
    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = -254999111802042445L;
    /** The execution id. */
    private Long executionId;
    /** The class name. */
    private String className;
    /** The super class name. */
    private String superClassName;
    /** The artifact id. */
    private Long artifactId;

    /**
     * Instantiates a new hmn dep service interface.
     * 
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public HmnDepServiceSuperClass() {
        super();
    }

    /**
     * Instantiates a new hmn dep service interface.
     * 
     * @param id
     *            the id
     * @param className
     *            the class name
     * @param superClassName
     *            the super class name
     * @param executionId
     *            the execution id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public HmnDepServiceSuperClass(Long id, String className, String superClassName, Long executionId, Long artifactId) {
        super(id);
        this.executionId = executionId;
        this.className = className;
        this.superClassName = superClassName;
        this.artifactId = artifactId;
    }

    /**
     * Gets the class name.
     * <p>
     * </p>
     * 
     * @return the class name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 12:50:13 PM
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the class name.
     * <p>
     * </p>
     * 
     * @param className
     *            the new class name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 12:50:13 PM
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * Gets the super class name.
     * <p>
     * </p>
     * 
     * @return the super class name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 2:24:21 PM
     */
    public String getSuperClassName() {
        return superClassName;
    }

    /**
     * Sets the super class name.
     * <p>
     * </p>
     * 
     * @param superClassName
     *            the new super class name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 2:24:21 PM
     */
    public void setSuperClassName(String superClassName) {
        this.superClassName = superClassName;
    }

    /**
     * Sets the execution id.
     * <p>
     * </p>
     * 
     * @param executionId
     *            the new execution id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 19, 2013 4:39:59 PM
     */
    public void setExecutionId(Long executionId) {
        this.executionId = executionId;
    }

    /**
     * Gets the execution id.
     * <p>
     * </p>
     * 
     * @return the execution id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 19, 2013 4:39:59 PM
     */
    public Long getExecutionId() {
        return executionId;
    }

    /**
     * @author U079754 A. Emre Zorlu
     * @since Jun 7, 2016
     * @param artifactId
     *            the artifactId to set
     */
    public void setArtifactId(Long artifactId) {
        this.artifactId = artifactId;
    }

    /**
     * @author U079754 A. Emre Zorlu
     * @since Jun 7, 2016
     * @return the artifactId
     */
    public Long getArtifactId() {
        return artifactId;
    }
}
