package com.sgo.depanalyze.hibernate.datamodel;

/**
 * DepHmnArtifacts generated by hbm2java.
 * 
 * @author U065352-Selçuk Giray ÖZDAMAR
 * @since Nov 11, 2013 10:14:07 AM
 */
public abstract class HmnDepDatamodel implements java.io.Serializable {
    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1047977059330230946L;
    /** The id. */
    private Long id;

    /**
     * Instantiates a new hmn dep datamodel.
     * 
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Dec 3, 2013 9:10:43 AM
     */
    public HmnDepDatamodel() {
        super();
    }

    /**
     * Instantiates a new hmn dep execution.
     * 
     * @param id
     *            the id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public HmnDepDatamodel(Long id) {
        super();
        this.id = id;
    }

    /**
     * Gets the id.
     * <p>
     * </p>
     * 
     * @return the id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the id.
     * <p>
     * </p>
     * 
     * @param id
     *            the new id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setId(Long id) {
        this.id = id;
    }
}
