package com.sgo.depanalyze.hibernate.datamodel;

/**
 * DepHmnServiceMethods generated by hbm2java.
 * 
 * @author U065352-Selçuk Giray ÖZDAMAR
 * @since Nov 11, 2013 10:14:07 AM
 */
public class HmnDepGlobalVariableUse extends HmnDepDatamodel implements java.io.Serializable {
    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1884051024729077651L;
    /** The execution id. */
    private Long executionId;
    /** The artifact id. */
    private Long artifactId;
    /** The service class name. */
    private String className;
    /** The method name. */
    private String methodName;
    /** The usage type. */
    private String usageType;
    /** The field name. */
    private String fieldName;
    /** The field type. */
    private String fieldType;
    /** The reference type. */
    private String referenceType;
    /** The dep level. */
    private Integer depLevel;
    /** The dep path. */
    private String depPath;

    /**
     * Gets the execution id.
     * 
     * @return the execution id
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public Long getExecutionId() {
        return executionId;
    }

    /**
     * Sets the execution id.
     * 
     * @param executionId
     *            the new execution id
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public void setExecutionId(Long executionId) {
        this.executionId = executionId;
    }

    /**
     * Gets the artifact id.
     * 
     * @return the artifact id
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public Long getArtifactId() {
        return artifactId;
    }

    /**
     * Sets the artifact id.
     * 
     * @param artifactId
     *            the new artifact id
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public void setArtifactId(Long artifactId) {
        this.artifactId = artifactId;
    }

    /**
     * Gets the class name.
     * 
     * @return the class name
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the class name.
     * 
     * @param className
     *            the new class name
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * Gets the method name.
     * 
     * @return the method name
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public String getMethodName() {
        return methodName;
    }

    /**
     * Sets the method name.
     * 
     * @param methodName
     *            the new method name
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    /**
     * Gets the field name.
     * 
     * @return the field name
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * Sets the field name.
     * 
     * @param fieldName
     *            the new field name
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    /**
     * Gets the field type.
     * 
     * @return the field type
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public String getFieldType() {
        return fieldType;
    }

    /**
     * Sets the field type.
     * 
     * @param fieldType
     *            the new field type
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public void setFieldType(String fieldType) {
        this.fieldType = fieldType;
    }

    /**
     * Gets the reference type.
     * 
     * @return the reference type
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public String getReferenceType() {
        return referenceType;
    }

    /**
     * Sets the reference type.
     * 
     * @param referenceType
     *            the new reference type
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public void setReferenceType(String referenceType) {
        this.referenceType = referenceType;
    }

    /**
     * Gets the dep level.
     * 
     * @return the dep level
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public Integer getDepLevel() {
        return depLevel;
    }

    /**
     * Sets the dep level.
     * 
     * @param depLevel
     *            the new dep level
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public void setDepLevel(Integer depLevel) {
        this.depLevel = depLevel;
    }

    /**
     * Gets the dep path.
     * 
     * @return the dep path
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public String getDepPath() {
        return depPath;
    }

    /**
     * Sets the dep path.
     * 
     * @param depPath
     *            the new dep path
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public void setDepPath(String depPath) {
        this.depPath = depPath;
    }

    /**
     * Sets the usage type.
     * 
     * @param usageType
     *            the new usage type
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public void setUsageType(String usageType) {
        this.usageType = usageType;
    }

    /**
     * Gets the usage type.
     * 
     * @return the usage type
     * @author Selçuk Giray ÖZDAMAR
     * @since Jun 23, 2016
     */
    public String getUsageType() {
        return usageType;
    }
}
