/*
 * @author U079754 A. Emre Zorlu
 * @date Jun 1, 2016
 */
package com.sgo.depanalyze.hibernate.datamodel;

// Generated Nov 1, 2013 12:04:05 PM by Hibernate Tools 3.4.0.CR1
/**
 * DepHmnNqDepend generated by hbm2java.
 * 
 * @author U065352-Selçuk Giray ÖZDAMAR
 * @since Nov 11, 2013 10:14:07 AM
 */
public class HmnDepNqDependency extends HmnDepDatamodel implements java.io.Serializable {
    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 3811298632341363968L;
    /** The service class. */
    private String serviceClass;
    /** The service method. */
    private String serviceMethod;
    /** The query name. */
    private String queryName;
    /** The dependency level. */
    private Integer dependencyLevel;
    /** The dependency path. */
    private String dependencyPath;
    /** The execution id. */
    private Long executionId;
    /** The artifact id. */
    private Long artifactId;

    /**
     * Instantiates a new hmn dep nq dependency.
     * 
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public HmnDepNqDependency() {
        super();
    }

    /**
     * Instantiates a new hmn dep nq dependency.
     * 
     * @param id
     *            the id
     * @param serviceClass
     *            the service class
     * @param serviceMethod
     *            the service method
     * @param queryName
     *            the query name
     * @param depLevel
     *            the dep level
     * @param depPath
     *            the dep path
     * @param executionId
     *            the execution id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public HmnDepNqDependency(Long id, String serviceClass, String serviceMethod, String queryName, Integer depLevel, String depPath, Long executionId, Long artifactId) {
        super(id);
        this.executionId = executionId;
        this.serviceClass = serviceClass;
        this.serviceMethod = serviceMethod;
        this.queryName = queryName;
        this.dependencyLevel = depLevel;
        this.dependencyPath = depPath;
        this.artifactId = artifactId;
    }

    /**
     * Gets the service class.
     * <p>
     * </p>
     * 
     * @return the service class
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public String getServiceClass() {
        return this.serviceClass;
    }

    /**
     * Sets the service class.
     * <p>
     * </p>
     * 
     * @param serviceClass
     *            the new service class
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setServiceClass(String serviceClass) {
        this.serviceClass = serviceClass;
    }

    /**
     * Gets the service method.
     * <p>
     * </p>
     * 
     * @return the service method
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public String getServiceMethod() {
        return this.serviceMethod;
    }

    /**
     * Sets the service method.
     * <p>
     * </p>
     * 
     * @param serviceMethod
     *            the new service method
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setServiceMethod(String serviceMethod) {
        this.serviceMethod = serviceMethod;
    }

    /**
     * Gets the query name.
     * <p>
     * </p>
     * 
     * @return the query name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public String getQueryName() {
        return this.queryName;
    }

    /**
     * Sets the query name.
     * <p>
     * </p>
     * 
     * @param queryName
     *            the new query name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setQueryName(String queryName) {
        this.queryName = queryName;
    }

    /**
     * Gets the dependency level.
     * <p>
     * </p>
     * 
     * @return the dependency level
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public Integer getDependencyLevel() {
        return dependencyLevel;
    }

    /**
     * Sets the dependency level.
     * <p>
     * </p>
     * 
     * @param dependencyLevel
     *            the new dependency level
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setDependencyLevel(Integer dependencyLevel) {
        this.dependencyLevel = dependencyLevel;
    }

    /**
     * Gets the dependency path.
     * <p>
     * </p>
     * 
     * @return the dependency path
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public String getDependencyPath() {
        return dependencyPath;
    }

    /**
     * Sets the dependency path.
     * <p>
     * </p>
     * 
     * @param dependencyPath
     *            the new dependency path
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setDependencyPath(String dependencyPath) {
        this.dependencyPath = dependencyPath;
    }

    /**
     * Sets the execution id.
     * <p>
     * </p>
     * 
     * @param executionId
     *            the new execution id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 19, 2013 4:38:53 PM
     */
    public void setExecutionId(Long executionId) {
        this.executionId = executionId;
    }

    /**
     * Gets the execution id.
     * <p>
     * </p>
     * 
     * @return the execution id
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 19, 2013 4:38:53 PM
     */
    public Long getExecutionId() {
        return executionId;
    }

    /**
     * @author U079754 A. Emre Zorlu
     * @since Jun 1, 2016
     * @param artifactId
     *            the artifactId to set
     */
    public void setArtifactId(Long artifactId) {
        this.artifactId = artifactId;
    }

    /**
     * @author U079754 A. Emre Zorlu
     * @since Jun 1, 2016
     * @return the artifactId
     */
    public Long getArtifactId() {
        return artifactId;
    }
}
