/*
 * @author U079754 A. Emre Zorlu
 * @date May 27, 2016
 */
package com.sgo.depanalyze.hibernate.datamodel;

// TODO: Auto-generated Javadoc
// Generated Oct 24, 2013 4:00:26 PM by Hibernate Tools 3.4.0.CR1
/**
 * DepHmnServiceMethods generated by hbm2java.
 * 
 * @author U065352-Selçuk Giray ÖZDAMAR
 * @since Nov 11, 2013 10:14:07 AM
 */
public class HmnDepServiceMethod extends HmnDepDatamodel implements java.io.Serializable {
    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1884051024729077651L;
    /** The execution id. */
    private Long executionId;
    /** The service class name. */
    private String className;
    /** The interface name. */
    private String interfaceName;
    /** The method name. */
    private String methodName;
    /** The signature. */
    private String signature;
    /** The digest. */
    private String digest;
    /** The artifact id. */
    private Long artifactId;

    /**
     * Instantiates a new hmn dep service method.
     * 
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public HmnDepServiceMethod() {
        super();
    }

    /**
     * Instantiates a new hmn dep service method.
     * 
     * @param executionId
     *            the execution id
     * @param className
     *            the class name
     * @param interfaceName
     *            the interface name
     * @param methodName
     *            the method name
     * @param signature
     *            the signature
     * @param digest
     *            the digest
     * @param artifactId
     *            the artifact id
     * @author U079754 A. Emre Zorlu
     * @since May 31, 2016
     */
    // /**
    // * Instantiates a new hmn dep service method.
    // *
    // * @param id
    // * the id
    // * @param serviceId
    // * the service id
    // * @param methodName
    // * the method name
    // * @param signature
    // * the signature
    // * @author U065352-Selçuk Giray ÖZDAMAR
    // * @since Nov 11, 2013 10:14:07 AM
    // */
    // public HmnDepServiceMethod(Long id, Long serviceId, String methodName, String signature) {
    // super(id);
    // this.serviceId = serviceId;
    // this.methodName = methodName;
    // this.signature = signature;
    // }
    /**
     * Gets the method name.
     * <p>
     * </p>
     * 
     * @return the method name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public String getMethodName() {
        return this.methodName;
    }

    /**
     * @author U079754 A. Emre Zorlu
     * @since May 31, 2016
     * @param executionId
     * @param className
     * @param interfaceName
     * @param methodName
     * @param signature
     * @param digest
     * @param artifactId
     */
    public HmnDepServiceMethod(Long executionId, String className, String interfaceName, String methodName, String signature, String digest, Long artifactId) {
        super();
        this.executionId = executionId;
        this.className = className;
        this.interfaceName = interfaceName;
        this.methodName = methodName;
        this.signature = signature;
        this.digest = digest;
        this.artifactId = artifactId;
    }

    /**
     * Sets the method name.
     * <p>
     * </p>
     * 
     * @param methodName
     *            the new method name
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setMethodName(String methodName) {
        this.methodName = methodName;
    }

    /**
     * Gets the signature.
     * <p>
     * </p>
     * 
     * @return the signature
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public String getSignature() {
        return this.signature;
    }

    /**
     * Sets the signature.
     * <p>
     * </p>
     * 
     * @param signature
     *            the new signature
     * @author U065352-Selçuk Giray ÖZDAMAR
     * @since Nov 11, 2013 10:14:07 AM
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * Gets the ınterface name.
     * <p>
     * </p>
     * 
     * @return the ınterface name
     * @author U065352 - SELÇUK GİRAY ÖZDAMAR
     * @since 30.Haz.2014 08:39:44
     */
    public String getInterfaceName() {
        return interfaceName;
    }

    /**
     * Sets the ınterface name.
     * <p>
     * </p>
     * 
     * @param interfaceName
     *            the new ınterface name
     * @author U065352 - SELÇUK GİRAY ÖZDAMAR
     * @since 30.Haz.2014 08:39:44
     */
    public void setInterfaceName(String interfaceName) {
        this.interfaceName = interfaceName;
    }

    /**
     * Gets the digest.
     * 
     * @return the digest
     * @author Selçuk Giray ÖZDAMAR
     * @since May 25, 2016
     */
    public String getDigest() {
        return digest;
    }

    /**
     * Sets the digest.
     * 
     * @param digest
     *            the new digest
     * @author Selçuk Giray ÖZDAMAR
     * @since May 25, 2016
     */
    public void setDigest(String digest) {
        this.digest = digest;
    }

    /**
     * Sets the execution id.
     * 
     * @param executionId
     *            the new execution id
     * @author Selçuk Giray ÖZDAMAR
     * @since May 25, 2016
     */
    public void setExecutionId(Long executionId) {
        this.executionId = executionId;
    }

    /**
     * Gets the execution id.
     * 
     * @return the execution id
     * @author Selçuk Giray ÖZDAMAR
     * @since May 25, 2016
     */
    public Long getExecutionId() {
        return executionId;
    }

    /**
     * Sets the class name.
     * 
     * @param className
     *            the new class name
     * @author Selçuk Giray ÖZDAMAR
     * @since May 25, 2016
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * Gets the class name.
     * 
     * @return the class name
     * @author Selçuk Giray ÖZDAMAR
     * @since May 25, 2016
     */
    public String getClassName() {
        return className;
    }

    /**
     * @author U079754 A. Emre Zorlu
     * @since May 27, 2016
     * @param artifactId
     *            the artifactId to set
     */
    public void setArtifactId(Long artifactId) {
        this.artifactId = artifactId;
    }

    /**
     * @author U079754 A. Emre Zorlu
     * @since May 27, 2016
     * @return the artifactId
     */
    public Long getArtifactId() {
        return artifactId;
    }
}
