SET DEFINE OFF;
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('APP_SERVER_HOSTNAME', 'opchrmntst2');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('APP_SERVER_PASSWORD', 'harmoni');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('APP_SERVER_USERNAME', 'loguser');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('BEINF_LOCAL_PATH', 'd:/temp_selcuk/be_inf_jars');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('BEINF_REMOTE_PATH', '/Shared_Libraries/be_inf/');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('BELIBS_LOCAL_PATH', 'd:/temp_selcuk/be_test_jars');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('BELIBS_REMOTE_PATH', '/Shared_Libraries/be/');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('FELIBS_LOCAL_PATH', 'd:/temp_selcuk/fe_test_jars');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('FELIBS_REMOTE_PATH', '/WebSphere/AppServer/profiles/AppSrv01/installedApps/opcbamprd1Cell01/CDM.ear/WebNBA.war/WEB-INF/lib/');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('FTP_UPDATE_ENABLE', 'N');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('RUN_PARALLEL', 'Y');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('THIRDPARTY_LOCAL_PATH', 'd:/temp_selcuk/thirdparty');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('THIRDPARTY_REMOTE_PATH', '/Shared_Libraries/thirdparty/');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('DEPANALYZE_LOGGER_LEVEL', 'INFO');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('BE_SCAN_THREAD_COUNT', '20');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('FE_SCAN_THREAD_COUNT', '20');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('BACKUP_FE_DEPENDENCY_QUERY', 'INSERT INTO HMNDEP_FE_DEPENDENCY_HIST (
   EXECUTION_ID, ARTIFACT_ID, SOURCE_CLASS, SOURCE_METHOD, SOURCE_SIGNATURE, 
   TARGET_SERVICE, TARGET_METHOD, TARGET_SIGNATURE) 
 SELECT EXECUTION_ID, ARTIFACT_ID, SOURCE_CLASS, SOURCE_METHOD, SOURCE_SIGNATURE, 
   TARGET_SERVICE, TARGET_METHOD, TARGET_SIGNATURE
   FROM HMNDEP_FE_DEPENDENCIES
  ORDER BY ID');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('BACKUP_SERVICE_DEPENDENCY_QUERY', 'INSERT INTO HMNDEP_SERVICE_DEPENDENCY_HIST (EXECUTION_ID,
                                            ARTIFACT_ID,
                                            CALLER_CLASS,
                                            CALLER_METHOD,
                                            CALLER_SIGNATURE,
                                            TARGET_SERVICE,
                                            TARGET_METHOD,
                                            TARGET_SIGNATURE,
                                            DEPENDENCY_LEVEL,
                                            DEPENDENCY_PATH)
     SELECT EXECUTION_ID,
            ARTIFACT_ID,
            CALLER_CLASS,
            CALLER_METHOD,
            CALLER_SIGNATURE,
            TARGET_SERVICE,
            TARGET_METHOD,
            TARGET_SIGNATURE,
            DEPENDENCY_LEVEL,
            DEPENDENCY_PATH
       FROM HMNDEP_SERVICE_DEPENDENCIES
   ORDER BY ID');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('BACKUP_ARTIFACTS_QUERY', 'INSERT INTO HMNDEP_ARTIFACT_HIST (ARTIFACT_NAME, ARTIFACT_TYPE, EXECUTION_ID)
     SELECT ARTIFACT_NAME, ARTIFACT_TYPE, EXECUTION_ID
       FROM HMNDEP_ARTIFACTS
   ORDER BY ID ');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('BACKUP_NQ_DEPENDENCIES_QUERY', 'INSERT INTO HMNDEP_NQ_DEPENDENCY_HIST (SERVICE_CLASS,
                                       SERVICE_METHOD,
                                       QUERY_NAME,
                                       DEPENDENCY_LEVEL,
                                       DEPENDENCY_PATH,
                                       EXECUTION_ID)
     SELECT SERVICE_CLASS,
            SERVICE_METHOD,
            QUERY_NAME,
            DEPENDENCY_LEVEL,
            DEPENDENCY_PATH,
            EXECUTION_ID
       FROM HMNDEP_NQ_DEPENDENCIES
   ORDER BY ID');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('BACKUP_PLSQL_DEPENDENCIES_QUERY', 'INSERT INTO HMNDEP_PLSQL_DEPENDENCY_HIST (SERVICE_CLASS,
                                          SERVICE_METHOD,
                                          PACKAGE_NAME,
                                          PROC_NAME,
                                          DEPENDENCY_LEVEL,
                                          DEPENDENCY_PATH,
                                          EXECUTION_ID)
     SELECT SERVICE_CLASS,
            SERVICE_METHOD,
            PACKAGE_NAME,
            PROC_NAME,
            DEPENDENCY_LEVEL,
            DEPENDENCY_PATH,
            EXECUTION_ID
       FROM HMNDEP_PLSQL_DEPENDENCIES
   ORDER BY ID');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('BACKUP_SERVICE_CLASSES_QUERY', 'INSERT INTO HMNDEP_SERVICE_CLASSES_HIST (CLASS_NAME,
                                         ARTIFACT_ID,
                                         EXECUTION_ID)
     SELECT CLASS_NAME, ARTIFACT_ID, EXECUTION_ID
       FROM HMNDEP_SERVICE_CLASSES
   ORDER BY ID');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('BACKUP_SERVICE_INTERFACES_QUERY', 'INSERT INTO HMNDEP_SERVICE_INTERFACE_HIST (CLASS_NAME, IMPLEMENTS, EXECUTION_ID)
     SELECT CLASS_NAME, IMPLEMENTS, EXECUTION_ID
       FROM HMNDEP_SERVICE_INTERFACES
   ORDER BY ID');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('BACKUP_SERVICE_SUPERCLASSES_QUERY', 'INSERT INTO HMNDEP_SERVICE_SUPERCLASS_HIST (CLASS_NAME,
                                            SUPER_CLASS,
                                            EXECUTION_ID)
     SELECT CLASS_NAME, SUPER_CLASS, EXECUTION_ID
       FROM HMNDEP_SERVICE_SUPERCLASSES
   ORDER BY ID');
Insert into CBSLIVE.HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('BACKUP_ENABLE', 'Y');
   
Insert into HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('QUERY_COMPARE_HISTORY_FE_DEP', 'SELECT A.HISTORY_COUNT,B.DEPENDENCY_COUNT 
  FROM
   (SELECT COUNT(*) HISTORY_COUNT 
      FROM HMNDEP_FE_DEPENDENCY_HIST H
     WHERE EXECUTION_ID = (SELECT MAX(EXECUTION_ID) FROM HMNDEP_FE_DEPENDENCY_HIST)) A,
   (SELECT COUNT(*) DEPENDENCY_COUNT 
      FROM HMNDEP_FE_DEPENDENCIES) B');
Insert into HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('QUERY_COMPARE_HISTORY_NQ_DEP', 'SELECT A.HISTORY_COUNT,B.DEPENDENCY_COUNT 
  FROM
   (SELECT COUNT(*) HISTORY_COUNT 
      FROM HMNDEP_NQ_DEPENDENCY_HIST H
     WHERE EXECUTION_ID = (SELECT MAX(EXECUTION_ID) FROM HMNDEP_NQ_DEPENDENCY_HIST)) A,
   (SELECT COUNT(*) DEPENDENCY_COUNT 
      FROM HMNDEP_NQ_DEPENDENCIES) B');
Insert into HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('QUERY_COMPARE_HISTORY_PLSQL_DEP', 'SELECT A.HISTORY_COUNT,B.DEPENDENCY_COUNT 
  FROM
   (SELECT COUNT(*) HISTORY_COUNT 
      FROM HMNDEP_PLSQL_DEPENDENCY_HIST H
     WHERE EXECUTION_ID = (SELECT MAX(EXECUTION_ID) FROM HMNDEP_PLSQL_DEPENDENCY_HIST)) A,
   (SELECT COUNT(*) DEPENDENCY_COUNT 
      FROM HMNDEP_PLSQL_DEPENDENCIES) B');
Insert into HMNDEP_PARAMETERS
   (PARAM_NAME, PARAM_VALUE)
 Values
   ('QUERY_COMPARE_HISTORY_SERVICE_DEP', 'SELECT A.HISTORY_COUNT,B.DEPENDENCY_COUNT 
  FROM
   (SELECT COUNT(*) HISTORY_COUNT 
      FROM HMNDEP_SERVICE_DEPENDENCY_HIST H
     WHERE EXECUTION_ID = (SELECT MAX(EXECUTION_ID) FROM HMNDEP_SERVICE_DEPENDENCY_HIST)) A,
   (SELECT COUNT(*) DEPENDENCY_COUNT 
      FROM HMNDEP_SERVICE_DEPENDENCIES) B');
      
COMMIT;
